#+TITLE: trello-helper — Moving information between Trello and Emacs Org
#+OPTIONS: H:2

** Goal

This project aims [[http://orgmode.org/][Org (an Emacs mode)]] as a way for consulting or
searching among [[https://trello.com/][Trello cards]].  *trello-helper* is the name of the Python
program which, using the Trello API, fetches information from Trello.

See Antoine Dumont's nice [[http://adumont.fr/blog/org-trello-sync-your-org-file-to-trello/][org-trello]] project for a more comprehensive,
real-time, 2-way sync, Emacs only solution.

** Installation

Install file =trello-helper= as an executable script somewhere on your
usual program search path.  It assumes that *python*, as a program name,
triggers Python 2.x (I only tried with Python 2.7.5).  The program
depends on two Python modules: *py-trello* and a patched version of
*python-oauth2*.  Here is a recipe installing both:

  #+BEGIN_SRC sh
    git clone https://github.com/tylerwilliams/python-oauth2
    (cd python-oauth2/ && python setup.py install)
    git clone https://github.com/sarumont/py-trello
    (cd py-trello/ && python setup.py install)
  #+END_SRC

OAuth2 credentials for your Trello board should be obtained and preset
within file =~/.trello/config.ini=, like this:

  #+BEGIN_EXAMPLE
    [trello]
    key = 0123456789abcdef0123456789abcdef
    token = 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  #+END_EXAMPLE

replacing the hexadecimal values appropriately, of course.  Visit the
page about [[https://trello.com/1/appKey/generate][Developer API Keys]] to get the needed values.

Here is some Emacs Lisp code which hides information about Trello ids.
You may put the following lines in your =~/.emacs= file:

  #+BEGIN_SRC elisp
    (defun my-org-mode-hook ()
      (font-lock-add-keywords
       nil '((" *:PROPERTIES: {\"orgtrello-id\":[^}\n]+}"
              (0 (add-text-properties (match-beginning 0) (match-end 0)
                                      '(invisible org-link)))))))

    (add-hook 'org-mode-hook 'my-org-mode-hook)
  #+END_SRC

** Usage

To get an index file reaching all you Trello boards, do something like:

  #+BEGIN_SRC sh
    trello-helper > boards.org
  #+END_SRC

To initialize a copy of a Trello board named =BOARD NAME=, do:

  #+BEGIN_SRC sh
    trello-helper 'BOARD NAME' > board_name.org
  #+END_SRC

** Random notes

- To ease file inter-operability a tiny bit, and some collaboration
  with Antoine, properties are named as in *org-trello*.

- The tool works completely off-line.  There is no real-time
  communication yet between Emacs and *trello-helper*.

- Next might be a mild transcription from Markdown to Org markup.

** History

This is a rewrite of an old unpublished tool of mine, named
*fetch-trello*.  It was using the Trello API to fetch all available
Trello boards at once and turn them into a single Org format file,
also providing diffs with the previous such Org file.  The tool was
less useful than I expected: the result was a bit bulky, diffs were
requiring too much scrutiny, and at the time, the Trello site was a
bit flaky.

Later, Antoine published *org-trello*, which is enthusiasming in many
ways, especially for me by showing it is much more natural to use one
Org file per Trello board, quite clever to use Trello ids to automate
the merging of differences, useful to set a 2-way link rather than my
pull-only.  Yet, *org-trello* does not fulfill all my needs.  One one
hand, I'd like a different structuring in Org for Trello data, the
capability of adding my own local-only comments with no danger of
losing them later, and automated transcription between Markdown and
Org markup.  On the other hand, I'd like something technically easier:
Emacs Lisp is too heavy in many ways, *org-trello* depends on many
packages (among which a precise version of Org which is older than the
version I use — a weakness in the Emacs packaging system?), and uses
asynchronous updates (distracting and difficult to rightly implement).
